version: "2"
services:
  gnucashdatabase:
    image: mysql:5.7
    ports:
      - 3306:3306
    expose:
      - 3306
    volumes:
      - ./gnucashdata:/docker-entrypoint-initdb.d/
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_USER=gnucash
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=gnucash
#  flask:
#    build:
#      context: .
#      dockerfile: flask_app/Dockerfile
#    image: flask_app:latest
#    ports:
#      - 5000:5000
#    expose:
#      - 5000

